### ISSUE TITLE
ACPI issues after SMP update

### ISSUE THREAD

**Issue by wilsonk** [PowerNex/PowerNex#76]
Hello Dan,

I am getting some errors after the recent SMP code update. With VBox I get a page fault (after a lengthy wait...VBox boots quite slowly??)

The VBox output is:
```
.
.
.
[0][+] data.multiboot2@568>     name: '.strtab'(idx: 9), type: 3, flags: 0x0, addr: 0x00000000_00635180, offset: 0x00\
000000_005363D8, size: 0x2AD5D, link: 0, info: 0, addralign: 0x1, entsize: 0x0
[0][+] data.multiboot2@568>     name: '.shstrtab'(idx: 17), type: 3, flags: 0x0, addr: 0x00000000_00152B70, offset: 0\
x00000000_00561135, size: 0xDC, link: 0, info: 0, addralign: 0x1, entsize: 0x0
[0][+] data.multiboot2@507> Multiboot2TagBasicMeminfo: lower:0x00000000_0000027F, upper: 0x00000000_001FFBC0
[0][+] data.multiboot2@514> Multiboot2TagBootdev: biosdev:224, slice: 4294967295, part: 4294967295
[0][+] data.multiboot2@538> Multiboot2TagFramebuffer: addr: 0x00000000_000B8000, pitch: 160, width: 80, height: 25, b\
pp: 16, type: egaText
[0][+] data.multiboot2@640> Multiboot2TagNewACPI: rsdp: 0x0000_0000_00C1_A7D8
[0][*] arch.amd64.acpi@515> ACPI/RSDP OEM is: VBOX
[0][!] arch.amd64.paging@606> ===> PAGE FAULT
                          | RIP = 0x00000000_0010DE84 (_D4arch5amd644acpi9SDTHeader5validMFNdNeZb+0x50)
RAX = 0x00000000_7FFF0030 | RBX = 0x00000000_00C1A7D8
RCX = 0x00000000_7FFF0030 | RDX = 0x00000000_001403F8
RDI = 0x00000000_7FFF0030 | RSI = 0x00000000_7FFF0030
RSP = 0x00000000_00174D9C | RBP = 0x00000000_00174DEC
 R8 = 0x00000000_00174CAC |  R9 = 0x00000000_00000203
R10 = 0x00000000_00000000 | R11 = 0x00000000_00000000
R12 = 0x00000000_00000000 | R13 = 0x00000000_00000000
R14 = 0x00000000_00000000 | R15 = 0x00000000_00000000
 CS = 0x00000000_00000008 |  SS = 0x00000000_00000010
CR0 = 0x00000000_80010013 | CR2 = 0x00000000_7FFF0034
CR3 = 0x00000000_0016A000 | CR4 = 0x00000000_000006A0
Flags = 0x210206
Errorcode: 0x0 ( NotPresent Read KernelMode )
PDP Mode: RWX
PD Mode:
PT Mode:
Page Mode:

STACKTRACE:
        [0x106CFE] _D4arch5amd646paging12_onPageFaultFNfPS4arch5amd648register9RegistersZv+0x1586
        [0x103FD2] _D4arch5amd643idt3IDT10isrHandlerUNePS4arch5amd648register9RegistersZv+0x132
        [0x103E80] _D4arch5amd643idt3IDT9isrCommonUNeZv+0x20
        [0x10F682] _D4arch5amd644acpi4ACPI7initNewFNeAhZv+0x112
        [0x13F31A] main+0xDA
        [0x100097] boot64BSP+0x21

```

 and with qemu I get a missing  ```_S5_``` entry.

The qemu output is:
```
.
.
.
[0][+] data.multiboot2@507> Multiboot2TagBasicMeminfo: lower:0x00000000_0000027F, upper: 0x00000000_0003FB7C
[0][+] data.multiboot2@514> Multiboot2TagBootdev: biosdev:224, slice: 4294967295, part: 4294967295
[0][+] data.multiboot2@538> Multiboot2TagFramebuffer: addr: 0x00000000_000B8000, pitch: 160, width: 80, height: 25, b\
pp: 16, type: egaText
[0][+] data.multiboot2@634> Multiboot2TagOldACPI: rsdp: 0x0000_0000_00C1_A7D8
[0][*] arch.amd64.acpi@478> ACPI/RSDP OEM is: BOCHS
[0][*] arch.amd64.acpi@80> signature: RSDT, length: 52, revision: 1, checksum: 184, oemID: BOCHS , oemTableID: BXPCRS\
DT, oemRevision: 1, creatorID: BXPC, creatorRevision: 1
[0][*] arch.amd64.paging@279> Mapping [0xFFFFFF00_00000000 - 0xFFFFFF00_00000FFF]
[0][*] arch.amd64.paging@279> Mapping [0xFFFFFF00_00000000 - 0xFFFFFF00_00000FFF]
[0][*] arch.amd64.acpi@80> signature: FACP, length: 116, revision: 1, checksum: 129, oemID: BOCHS , oemTableID: BXPCF\
ACP, oemRevision: 1, creatorID: BXPC, creatorRevision: 1
[0][*] arch.amd64.acpi@577> ACPI is now on!
[0][*] arch.amd64.paging@279> Mapping [0xFFFFFF00_00001000 - 0xFFFFFF00_00001FFF]
[0][*] arch.amd64.paging@279> Mapping [0xFFFFFF00_00001000 - 0xFFFFFF00_00002FFF]
[0][*] arch.amd64.acpi@80> signature: DSDT, length: 3028, revision: 1, checksum: 132, oemID: BOCHS , oemTableID: BXPC\
DSDT, oemRevision: 1, creatorID: BXPC, creatorRevision: 1
[0][*] arch.amd64.acpi@696> idx 981
[0][*] arch.amd64.acpi@696> idx 1018
[0][*] arch.amd64.acpi@696> idx 1041
[0][*] arch.amd64.acpi@696> idx 1055
[0][*] arch.amd64.acpi@696> idx 1073
[0][*] arch.amd64.acpi@696> idx 1091
[0][*] arch.amd64.acpi@696> idx 2377
[0][*] arch.amd64.acpi@696> idx -1
[0][!] arch.amd64.acpi@705> DSDT does not contain a _S5_

STACKTRACE:
        [0x10FEFD] _D4arch5amd644acpi4ACPI6acceptFNfPS4arch5amd644acpi4DSDTZv+0x1A9
        [0x10FA52] _D4arch5amd644acpi4ACPI6acceptFNfPS4arch5amd644acpi6FADTv1Zv+0x252
        [0x110AAC] _D4arch5amd644acpi4ACPI11_runHandlerFNePS4arch5amd644acpi9SDTHeaderZv+0x68
        [0x10F550] _D4arch5amd644acpi4ACPI7initOldFNeAhZv+0x2B8
        [0x13F34A] main+0x10A
        [0x100097] boot64BSP+0x21
```

I added a bit of debug output for the index but otherwise that should be the correct output.  Any thoughts?

Thanks,
Kelly

**Comment by Vild** [comment]
The current state of master is broken, I'm trying to figure it out, TLS seems to be broken.

VBox runs slowly because it will emulate real serial speeds instead of just going as fast as possible, also I haven't tried in a while, so that is probably why it is broken.

It's weird that you have problems with qemu, I haven't seen that before.
What qemu version are you running? Are you using the 'b' command from env.sh?

**Comment by wilsonk** [comment]
Ok, thanks Dan. I won't use VBox then. The qemu version I am using is 
```
qemu-x86_64 version 2.5.0 (Debian 1:2.5+dfsg-5ubuntu10.16), Copyright (c) 2003-2008 Fabrice Bellard
```
and I am using the b command to run it.

Thanks,
Kelly

**Comment by Vild** [comment]
I couldn't really find any of the problems you reported, everything works on my end (both vbox and qemu), but it could be something I fixed recently.
So if you can please try and compile and run master (9c06ec2).

**Comment by wilsonk** [comment]
Hmm, seems like the same problems with both qemu and VBox...ugh. Not sure what is going on. I pulled, cleaned and rebuilt to no avail.

**Comment by wilsonk** [comment]
DMD64 D Compiler v2.074.1 --- maybe the wrong compiler?

**Comment by Vild** [comment]
Try and run `./toolchainManager.d`, to make sure your toolchain is up-to-date

**Comment by wilsonk** [comment]
Oh, yeah right I forgot that I had a local copy of the cross compiler and that I had run that. Just grasping at straws here, as I have no idea why this is happening.

Now, of course, I never did try to build/run this before the SMP updates so this issues title might be a little misleading...maybe this problem would have existed before those updates, I don't know. Ugh, frustrating

**Comment by Vild** [comment]
I will make sure this is fixed for the next release, but for now it will be on my backlog, because I prioritize the development of PowerNex and school projects.
But I will post an iso soon here that you could try, so we can atleast see if the .iso you compiled is wrong or if it is something to do with the VMs.

**Comment by Vild** [comment]
Sorry about the delay, but here is a prebuilt one that works for me: https://powernexos.org/prebuilt/powernex-v0.2.0.r141.gc4048c1.iso

**Comment by wilsonk** [comment]
Ugh, exactly the same issues still :(  Which versions of qemu and VBox are you using? I assume you are running on Linux

**Comment by Vild** [comment]
QEMU emulator version 2.10.0
virtualbox 5.1.28
bochs 2.6.9
I'm running Arch

**Comment by wilsonk** [comment]
Hmmm, I have qemu version 2.5.0 and VBox 5.0.40. Maybe that is the problem. Sorry to be a bother, but those are the stock versions from apt on Linux Lite (Ubuntu 16.04 clone). I just wanted to see a record of this in case others run into this, as Ubuntu is a popular flavor :)

I will try updating both and let you know how it goes.

**Comment by wilsonk** [comment]
Pheww, finally. I got VBox to work after removing the stock 5.0.40 version and installing the 5.1.28 version (make sure to clean the previous version properly! ```sudo apt-get autoremove --purge virtualbox-5.1``` << need the --purge or it won't work propery). Still a little slow with the serial port turned on but not too bad.

Still having a slight problem with qemu-2.10.0 though? The graphical grub boot won't come up? It boots and runs to completion according to the log file, but I don't know why the graphical part won't come up. Oh well, I will just use VBox as long as it is working.

Once again, sorry to bother you...keep up the good work :)

**Comment by Vild** [comment]
Try and add  `-vga std` to the qemu command or something else that it takes (`qemu-system-x86_64 -help | grep -- -vga`)

**Comment by Vild** [comment]
Reopen this if the v0.3 (future) release contains this bug. It was probably just some buggy in development code.
